### ISSUE TITLE
Start when Idle doesn't work

### ISSUE THREAD

**Issue by JimKnightster** [grantemsley/MultiPoolMiner#11]
Is it ok to post issues here?

Start when idle doesn't seem to work on either of my systems.  I have set it to various levels and thje Idle time counter does work, but it doesn't start mining.

**Comment by grantemsley** [comment]
Yeah you can post issues here if they are specific to my fork.

I know the button and status lines aren't updating properly, but it should still start a minimized PowerShell window for the mining script.

You need to have PowerShell 6 installed, and make sure you have used the setup program so that all the configuration is in config.txt

Check that you can run multipoolminer.ps1 (not the .bat file) in PowerShell without any issues.

**Comment by JimKnightster** [comment]
Yup your right it does work.  I have another issue on the rig I was testing it on.

**Comment by grantemsley** [comment]
The status line does update when idle mining starts now.
