### ISSUE TITLE
newpoc: Suggestions/Ideas

### ISSUE THREAD

**Issue by grantemsley** [grantemsley/MultiPoolMiner#15]
I finally got a chance to take a good look at it!

- Create a function that handles reading and updating the miner's configuration section.  Then you don't have to repeat the same section of code for each one.  That function can also use a mutex like Write-Log does to ensure it's the only thing writing to config.txt at the time (it shouldn't be an issue normally, but if you accidentally started 2 copies of the script or something, it would probably corrupt config.txt).  The miner file could send it's default configuration as a parameter, and receive back the full configuration, after any necessary updates are handled.
- The amount of configuration added is going to be overwhelming for some - I'd simplify how much information is exposed to be user-configurable:
  - Remove `MinerBinaryInfo`, `Uri`, `UriManual`, and `WebLink` from the config.txt file - those can all be displayed in the setup program or in the script when a miner has to be downloaded manually, but don't need to be user configurable.  Just the MinerFileVersion to tell what version this configuration is for.
  - Remove those from the $Info.Settings section too - letting people change the download URL there is just going to cause support problems.  When there's a new version, we should be updating it and releasing a new miner file.  People testing newer versions should be advanced enough to be editing the miner files, not needing a GUI for it.
- I might want to rework how IgnoreHWModel and IgnoreDeviceID are handled in the settings - I won't know for sure exactly what I want until I get to writing that part of the setup program.  Ideally, I'd like it to have checkboxes or something for the cards that are actually in the system rather than make the user sort out the ID numbers.
- I see references to $Config.MinerInstancePerCardModel, but that's not in config.txt.  Do I just have to add it to config.txt or is that not fully setup yet?
- I'd like to start adding as much of this as I can, at least to my master branch, and ideally to the main project.  What parts do you think would be the easiest to add, that can stand on their own without too many changes at once?

**Comment by UselessGuru** [comment]
I have updated all miner files:

> Create a function that handles reading and updating the miner's configuration section.

Implemented for basic config. The update can vary from version to version, so no generalization possible

> That function can also use a mutex like Write-Log does

Implemented

> The amount of configuration added is going to be overwhelming for some - I'd simplify how much > > information is exposed to be user-configurable:
> Remove MinerBinaryInfo, Uri, UriManual, and WebLink from the config.txt file

Removed as requested.

> Remove those from the $Info.Settings section too

Done

> I might want to rework how IgnoreHWModel and IgnoreDeviceID are handled in the settings

The tooltip could show a list of values to use.

> I see references to $Config.MinerInstancePerCardModel, but that's not in config.txt.

$Config.MinerInstancePerCardModel should be added as a config item in setup. The current code implementation does not require it to be present. MPM will then just run shared miners.

**Comment by UselessGuru** [comment]
> What parts do you think would be the easiest to add, that can stand on their own without too many changes at once?

Quite easy are all new pool based settings:
ExcludeAlgorithm
ExcludeCoin / Coin
ExcludeCurrency / Currency
MinWorker
PoolFee
IgnorePoolFee
PricePenaltyFactor

The newpoc pool files are 'backwards' compatible with main. Some of the newpoc stuff is already in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435 pending.

On the miner side I think we are better off pushing the new miners one by one as they are already. Removing functionality could get complicated since a lot of it is interlinked. We better spend the time on testing. I see no easy step-by-step migration path.
All in all are the new mines fully compatible with the existing core.

In any case we need to add Add Get-Device, Get-DeviceSet and Get-CommandPerDevice to core. These are prerequisites for a number of features of the new miners.

The most challenging stuff is getting the miners to do miner-per-device. $Config.MinerInstancePerCardModel=$false disables it. As long as it remains disabled there are no direct compatiblitiy issues. One thing we have to be careful:
All new miners are AMD or CPU or NVIDIA only. They cannot work together with old mixed miners, e.g. eMiner which is for CPU&NVIDIA. We could add a compatibility flag to all old miners.
Some miners cannot even made miner-per-device compatible due to missing config possibilities (e.g. prospector does not support multiple API ports 👎 ).
