### ISSUE TITLE
readme/ install guide

### ISSUE THREAD

**Issue by m-bosch** [grantemsley/MultiPoolMiner#18]
Hi @grantemsley 

im very interested in your version of the MPM, but could you tell me what the differences are (globally) and what I need to configure differently?

I ask this because the readme etc is from the main/forked repo

**Comment by grantemsley** [comment]
My version is mostly a testing ground for stuff I'm working on getting added to the official MultiPoolMiner.  Eventually most of my changes make their way to the official version, but it takes awhile.

Right now the main differences are:

- I have a launcher that gives a nice GUI that will show the status of your remote workers, start and stop the script, and give you the option to automatically start when the system is idle (which is great for machines that aren't dedicated miners).
- The launcher doesn't use any command line parameters - so it is important that you edit config.txt to fill in all the needed information.  I'll put a sample of how mine is set below.
- Has a web interface for showing stats and pool balances while the script is running - click Open Web Interface in the launcher.  This is waiting to be merged with the official version
- Has a better updating script - just run update-dev.bat and it will automatically pull the latest changes from github, download any updated miners, and clear the benchmarks for just the miners that have changed so they get rebenchmarked
- If showminerwindow is enabled, you can see the miners windows, but they start minimized and don't steal focus from the current window
- Improvements to device detection
- CPU mining will be limited to half your CPU's cores to leave some processing power available for the script and GPU miners
- Optionally make the web interface remotely accessible so you can monitor it from another computer in your local network.  Your windows account needs to have a password for that to work, since it requires authentication.  It is NOT SAFE to open this up to access from the internet.
- A few extra miners - nothing significantly faster, just ones I've been testing to see if they were any better.


Here's my slightly censored config.txt file:

```
{
    "Miners":  {},
    "Wallet":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB",
    "MinerStatusKey":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB",
    "Currency":  ["BTC","CAD"],
    "WorkerName":  "GRANTNEW",
    "Region":  "US",
    "Pools":  {
	"AHashPool":  {"Worker":  "GRANTNEW","BTC":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB"},
	"Hashrefinery":  {"BTC":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB","Worker":  "GRANTNEW"},
	"MiningPoolHub":  {"Username":  "grantemsley","API_Key":  "censored","Worker":  "GRANTNEW"},
	"MiningPoolHubCoins":  {"Username":  "grantemsley","API_Key":  "censored","Worker":  "GRANTNEW"},
	"NiceHash":  {"Worker":  "GRANTNEW","BTC":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB"},
	"ZergPool":  {"BTC":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB","Worker":  "GRANTNEW"},
	"Zpool":  {"BTC":  "1BLXARB3GbKyEg8NTY56me5VXFsX2cixFB","Worker":  "GRANTNEW"}
    },
    "PoolName":  ["AHashPool","Hashrefinery","NiceHash","MiningPoolHubCoins","Zpool","MiningPoolHub","ZergPool"],
    "ExcludePoolName":  ["YiiMP","BlockMasters","BlazePool"],
    "Algorithm":  [],
    "ExcludeAlgorithm":  [],
    "MinerName":  ["Excavator"],
    "ExcludeMinerName":  [],
    "Donate":  10,
    "Interval":  60,
    "Delay":  10,
    "SSL":  false,
    "Watchdog":  true,
    "SwitchingPrevention":  3,
    "Proxy":  "",
    "ShowMinerWindow": true,
    "MinerStatusURL":  "https://multipoolminer.io/monitor/miner.php",
    "ShowPoolBalances": true,
    "ShowPoolBalancesExcludedPools": true,
    "UseFastestMinerPerAlgoOnly": false,
    "IgnoreMinerFee":  false,
    "RemoteAPI": false
}
```

**Comment by m-bosch** [comment]
Thank you for the fast response.

Does it have a high(er) risk on bugs or fails? like everyone I prefer 24/7 mining not 20/7 :-)


PS: Do you update new versions and miners from your repo or the main?

**Comment by m-bosch** [comment]
Do you update new versions and miners from your repo or the main?

**Comment by grantemsley** [comment]
I test it before I upload, but there's always the risk something fails.  It's up to you which you'd rather use.

When new miners come out, if I'm updating them myself they'll end up here first then get put in the main repo.  When others do it, I usually merge their PRs before the official one gets them, but not always.

**Comment by m-bosch** [comment]
Thanks again, I will download your repo this weekend. Can I maintain/keep the folder with the main MPM? or does this give issues with software?  

Why I ask this? because I can switch fast to execute an other start.bat file to compare :-)

**Comment by grantemsley** [comment]
You need to download it to a separate folder than the one you have the official MPM in.  As long as you don't try to start them both at the same time, they will be fine.  If you run the official one, make sure the launcher from mine is either closed or not set to start when idle.

**Comment by m-bosch** [comment]
I will! And of course I will let you know my experience.

Thanks in advance!

**Comment by m-bosch** [comment]
Hi @grantemsley,

is it better to download the latest version or the download from the master of your version? after work of today I will setup your fork on my miner.

**Comment by grantemsley** [comment]
Always download the master version.  Preferably using git, not just downloading the zip file - the update-dev.ps1 script uses git to check for updates in the master branch, and needs you to have checked it out with git.

**Comment by m-bosch** [comment]
hi @grantemsley a small question why did you prefer to exclude 'BlazePool', increase the delay and set the switch to 3?

my slightly censored config is like this atm: 
```
{
    "API_ID":  "",
    "API_Key":  "",
    "Currency":  ["EUR", "BTC", "USD"],
    "Delay":  3,
    "DeviceName":  ["NVIDIA"],
    "DisableAutoUpdate":  false,
    "Donate":  10,
    "ExcludeAlgorithm":  ["Lbry","Groestl","Sib","Blake2s","C11","Tribus","Skunk","Balloon","HMQ1725","Blakecoin"],
    "ExcludeMinerName":  [],
    "ExcludePoolName" : ["YiiMP","BlockMasters","AHashPool","Hashrefinery","Zpool"],
    "IgnoreMinerFee":  false,
    "Interval":  90,
    "MinerName":  [],
    "Miners":  { },
    "MinerStatusKey":  "1627368a-4c24-4820-ae1a-bd0b5a3b422d",
    "MinerStatusURL":  "https://multipoolminer.io/monitor/miner.php",
    "PoolName":  ["NiceHash","BlazePool","MiningPoolHub","ZergPool","MiningPoolHubCoins"],
    "Pools":  {
		"MiningPoolHub": {"Username": "baron1898", "API_Key": "censored", "Worker": "miner1"},
		"MiningPoolHubCoins": {"Username": "baron1898", "API_Key": "censored", "Worker": "miner1"},
		"NiceHash": {"Worker": "miner1", "BTC": "3LSr6zDjNk9VSMeryTMHwVZPf1b1XFYciD"},
		"ZergPool": {"LTC": "M94J8bw1BJWoks4rwPC24euPjZeNjFNZru","Worker": "miner1"},
		"Blazepool": { "BTC": "3A26LzJDcCRUdz1mdpPosiqCPwZj49iPrP", "Worker": "miner1"}
    },
    "Proxy":  "",
    "Region":  "Europe",
    "RemoteAPI":  false,
    "ShowMinerWindow":  true,
    "ShowPoolBalances":  true,
    "ShowPoolBalancesExcludedPools":  false,
    "SSL":  false,
    "SwitchingPrevention":  3,
    "UseFastestMinerPerAlgoOnly":  false,
    "UserName":  "baron1898",
    "VersionCompatibility":  "3",
    "Wallet":  "3A26LzJDcCRUdz1mdpPosiqCPwZj49iPrP",
    "Watchdog":  true,
    "WorkerName":  "miner1"
}
```

**Comment by grantemsley** [comment]
I increased delay because having it too low sometimes caused crashes while switching miners.

No particular reason for the switching prevention. Not sure what works best there.

Excluded blazepool because I already have plenty of pools and the more I split my mining across the more I have to wait for payouts.

**Comment by m-bosch** [comment]
OK thanks for the response. Thought maybe there was a particular reason to exclude it. :-)

**Comment by m-bosch** [comment]
ps edited my config to alphabetical order :-)

**Comment by m-bosch** [comment]
Hi @grantemsley do I need to fill in the API_KEY for miningpoolhub?

I did so far, but seems like miningpoolhubstats are off since I added the api key

`"MiningPoolHub": {"Username": "baron1898", "API_Key": "censored", "Worker": "miner1"},
		`

censored is of course set where the api key should be
